"""
The Verifier() class will check file integrity every time the game is loaded.
Please do not edit this file (and definitely don't delete it).
"""

# Imports
import os

# Constants
PATHS = (
    "config",
    ("config", "conf.toml"),
    "interfaces",
    "lang",
    "config_loader.py",
    "expression.py",
    "lang_loader.py",
    "main.py",
    "start.py",
    "term.py",
    "verifier.py",
    "utils",
    ("utils", "__init__.py"),
    ("utils", "text.py")
)

# Verifier
class Verifier:
    @staticmethod
    def verify():
        for path_element in PATHS:
            if not os.path.exists(os.path.join(*path_element if type(path_element) is list else path_element)):
                return False
        return True


# Function
def verify_handler_messages(language_data):
    try:
        for item in [
            "anErrorOccurredText",
            "couldNotLocateText",
            "couldNotImportText",
            "exceptionMessageFilledText",
            "ModuleNotFoundErrorText",
            "ImportErrorText",
            "pleaseReinstallText"
        ]:
            if item not in language_data["exceptionHandling"]:
                return False
        return True
    except KeyError:
        return False
