[meta]
author = "R1DF"
dateCreated = [18, 12, 2022]
description = "The official, preinstalled language pack for The Differentiation Quiz."
forVersion = "1.0.0"

[multipleUse]
closedQuestionAnswers = [
    "Yes",
    "No"
]

pressToContinue = "Press any key to continue..."
pressToExit = "Press any key to exit..."
enterToContinue = "Press Enter to continue..."
enterToExit = "Press Enter to exit..."

success = "Success"
error = "Error"

[exceptionHandling]
anErrorOccurredText = "An error occurred while running the program:"
couldNotLocateText = "Could not locate a necessary module to import."
couldNotImportText = "Could not import a class or a function from a module."
exceptionMessageFilledText = "Exception message: [EXCEPTION]"
ModuleNotFoundErrorText = "[ModuleNotFoundError]"
ImportErrorText = "[ImportError]"
pleaseReinstallText = "Please reinstall the game."

[menus]
[menus.mainMenu]
welcomeText = "Welcome to The Differentiation Quiz."
runningVersionText = "Running version v[VERSION]."
doWhatQueryText = "Please select an option:"
doWhatQueryChoices = [
    "Play",
    "Settings",
    "Check for updates",
    "Quit"
]
confirmQuitQuery = "Are you sure you want to quit?"

[menus.gameSetup]
difficultiesText = "Please look at the difficulties and their descriptions below before choosing one."
easyDifficultyDescription = """
Easy
- Powers only with natural numbers involved.
- Maximum amount of terms: 3.
- Questions can be skipped (won't count as correct).
- 7 questions.
"""

mediumDifficultyDescription = """
Medium
- Integer powers involved.
- Maximum amount of terms: 4.
- 3 skips allowed.
- Second order derivatives may appear.
- 10 questions.
"""

hardDifficultyDescription = """
Hard
- Integer powers involved.
- Maximum amount of terms: 5.
- No skips allowed.
- Third order derivatives may appear.
- Notation related questions appear.
- 13 questions.
"""

difficultiesQueryText = "Select difficulty:"
difficultiesQueryChoices = [
    "Easy",
    "Medium",
    "Hard",
    "Cancel"
]

[menus.gameLoading]
selectedDifficultyText = "Selected difficulty: [DIFFICULTY]"
generatingQuestionsText = "Generating [AMOUNT] questions..."
generatingQuestionText = "Generating question [N]..."
generationCompleteText = "Question generation complete."

[menus.game]
questionNumberText = "Question No. [N]"
firstOrderDerivativeQuestionText = "What is the derivative of the following expression?"
secondOrderDerivativeQuestionText = "What is the second-order derivative of the following expression?"
thirdOrderDerivativeQuestionText = "What is the third-order derivative of the following expression?"
isCorrectQuestionText = "Are the following equations correct?"
notationQuestionText = "Which of these is the correct complementary equation for this one?"
answerQueryText = "Select answer:"
skipChoiceText = "Skip"
correctAnswerText = "Correct!"
skippedText = "Question skipped."
incorrectAnswerText = "Incorrect!"
resultsText = "Your game results:"
questionResultText = "Question No. [N]:"
resultTextEntries = [
    "Correct",
    "Incorrect",
    "Skipped"
]
resultFractionText = "Correct answers: [CORRECT] out of [AMOUNT]."
resultPercentageText = "Percentage score: [N]%"


[menus.checkingUpdates]
testingSampleRequestText = "Sending sample request..."
requestPassedText = "Sample request passed."
noInternetErrorText = "Error: Please check your internet connection."
invalidStatusCodeText = "Error: Received invalid status code. [[CODE]]"
checkingForUpdatesText = "Checking for updates..."
latestVersionText = "You're on the latest version!\nNo upgrades needed."
upgradeNeededText = "An upgrade is available: [v.[OLD] --> v.[NEW]]"
versionNotesIntroducerText = "Version notes:"
getUpdatesLinkText = "Link to download updates:"
linkToCheckText = "You can manually check for updates with the following link:"
