[meta]
author = "R1DF"
dateCreated = [18, 12, 2022]
description = "The official, preinstalled language pack for The Differentiation Quiz."
forVersion = "1.0.0"

[multipleUse]
closedQuestionAnswers = [
    "Yes",
    "No"
]

pressToContinue = "Press any key to continue..."
pressToExit = "Press any key to exit..."
enterToContinue = "Press Enter to continue..."
enterToExit = "Press Enter to exit..."

[exceptionHandling]
anErrorOccurredText = "An error occurred while running the program:"
couldNotLocateText = "Could not locate a necessary module to import."
couldNotImportText = "Could not import a class or a function from a module."
exceptionMessageFilledText = "Exception message: [EXCEPTION]"
ModuleNotFoundErrorText = "[ModuleNotFoundError]"
ImportErrorText = "[ImportError]"
pleaseReinstallText = "Please reinstall the game."

[menus]
[menus.mainMenu]
welcomeText = "Welcome to The Differentiation Quiz."
runningVersionText = "Running version v[VERSION]."
doWhatQueryText = "Please select an option:"
doWhatQueryChoices = [
    "Play",
    "Settings",
    "Check for updates",
    "Quit"
]
confirmQuitQuery = "Are you sure you want to quit?"

[menus.gameSetup]
difficultiesText = "Please look at the difficulties and their descriptions below before choosing one."
easyDifficultyDescription = """
Easy
- Powers only with natural numbers involved.
- Maximum amount of terms: 3.
- Questions can be skipped (won't count as correct).
- 10 questions.
"""

mediumDifficultyDescription = """
Medium
- Whole powers involved (can be negative).
- Maximum amount of terms: 5.
- 3 skips allowed.
- Second order derivatives may appear.
- 13 questions.
"""

hardDifficultyDescription = """
Hard
- Any real power can be involved (negatives, decimals, or both included).
- Maximum amount of terms: 6.
- No skips allowed.
- Third order derivatives may appear.
- Notation related questions appear.
- 15 questions.
"""

difficultiesQueryText = "Select difficulty:"
difficultiesQueryChoices = [
    "Easy",
    "Medium",
    "Hard",
    "Cancel"
]

[menus.game]
firstOrderDerivativeQuestionText = "What is the derivative of the following function:"
secondOrderDerivativeQuestionText = "What is the second-order derivative of the following function:"
thirdOrderDerivativeQuestionText = "What is the third-order derivative of the following function:"
isCorrectlQuestionText = "Are the following equations correct?"
